import { Garment, PatternComponent } from './types';
import { calculateGarmentBounds, pathCommandsToSvgString } from './gradingEngine';

export interface SvgExportOptions {
  includeRulers?: boolean;
  includeGrainlines?: boolean;
  includeNotches?: boolean;
  includeLabels?: boolean;
  includeBounds?: boolean;
  strokeWidth?: number;
  unit?: 'mm' | 'cm';
}

/**
 * Generates production-ready standalone SVG file content
 * Contains structured vector groups for FRONT, BACK, SLEEVE, Grainlines, Notches, and Labels.
 */
export function generateGarmentSvg(
  garment: Garment,
  options: SvgExportOptions = {}
): string {
  const {
    includeGrainlines = true,
    includeNotches = true,
    includeLabels = true,
    includeBounds = false,
    strokeWidth = 1.5,
  } = options;

  const bounds = calculateGarmentBounds(garment);
  const viewBox = `${bounds.minX} ${bounds.minY} ${bounds.width} ${bounds.height}`;

  let svg = `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg xmlns="http://www.w3.org/2000/svg"
     xmlns:xlink="http://www.w3.org/1999/xlink"
     viewBox="${viewBox}"
     width="${bounds.width}mm"
     height="${bounds.height}mm"
     data-app="Easy Pattern CAD"
     data-garment="${garment.name}"
     data-size="${garment.currentSize}">
  
  <defs>
    <style>
      .cad-outline { fill: none; stroke: #1e293b; stroke-width: ${strokeWidth}; stroke-linejoin: round; stroke-linecap: round; }
      .cad-front { stroke: #2563eb; }
      .cad-back { stroke: #0284c7; }
      .cad-sleeve { stroke: #4f46e5; }
      .cad-grainline { stroke: #0f172a; stroke-width: 1.2; stroke-dasharray: 6 3; }
      .cad-notch { stroke: #ef4444; stroke-width: 2; }
      .cad-label { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, monospace; fill: #0f172a; font-size: 14px; font-weight: 600; }
      .cad-sublabel { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, monospace; fill: #64748b; font-size: 11px; }
      .cad-bounds { fill: none; stroke: #3b82f6; stroke-width: 1; stroke-dasharray: 4 4; opacity: 0.6; }
    </style>
    
    <marker id="grain-arrow" viewBox="0 0 10 10" refX="5" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
      <path d="M 0 0 L 10 5 L 0 10 z" fill="#0f172a" />
    </marker>
  </defs>

  <!-- Title & Metadata Block -->
  <g id="metadata-block">
    <text x="${bounds.minX + 25}" y="${bounds.minY + 30}" class="cad-label" font-size="16">
      ${garment.name.toUpperCase()} — SIZE ${garment.currentSize} (CAD EXPORT)
    </text>
    <text x="${bounds.minX + 25}" y="${bounds.minY + 48}" class="cad-sublabel">
      Generated by Easy Pattern CAD Engine • 1-Object Vector Model • Tolerance ±0.05mm
    </text>
  </g>
`;

  if (includeBounds) {
    svg += `
  <!-- Garment Bounding Box -->
  <rect x="${bounds.minX}" y="${bounds.minY}" width="${bounds.width}" height="${bounds.height}" class="cad-bounds" />
`;
  }

  // Iterate over Front, Back, Sleeve
  garment.components.forEach((component: PatternComponent) => {
    const groupX = garment.position.x + component.offset.x;
    const groupY = garment.position.y + component.offset.y;
    const pathD = pathCommandsToSvgString(component.paths);
    const colorClass =
      component.id === 'front'
        ? 'cad-front'
        : component.id === 'back'
        ? 'cad-back'
        : 'cad-sleeve';

    svg += `
  <!-- ================= ${component.name.toUpperCase()} ================= -->
  <g id="component-${component.id}" transform="translate(${groupX}, ${groupY})" data-component="${component.id}">
    <!-- Vector Pattern Boundary -->
    <path d="${pathD}" class="cad-outline ${colorClass}" />
`;

    // Grainline
    if (includeGrainlines && component.grainline) {
      svg += `
    <!-- Grainline -->
    <line x1="${component.grainline.start.x}" y1="${component.grainline.start.y}"
          x2="${component.grainline.end.x}" y2="${component.grainline.end.y}"
          class="cad-grainline" marker-start="url(#grain-arrow)" marker-end="url(#grain-arrow)" />
    <text x="${component.grainline.start.x + 8}" y="${(component.grainline.start.y + component.grainline.end.y) / 2}"
          class="cad-sublabel" transform="rotate(-90 ${component.grainline.start.x + 8} ${(component.grainline.start.y + component.grainline.end.y) / 2})">
      ${component.grainline.label}
    </text>
`;
    }

    // Notches
    if (includeNotches && component.notches) {
      svg += `    <!-- Pattern Notches -->\n`;
      component.notches.forEach((notch) => {
        // Render 10mm tick mark for notch
        svg += `    <line x1="${notch.x - 4}" y1="${notch.y - 4}" x2="${notch.x + 4}" y2="${notch.y + 4}" class="cad-notch" title="${notch.name || 'Notch'}" />\n`;
      });
    }

    // Labels
    if (includeLabels && component.labels) {
      svg += `    <!-- Pattern Labels & Information -->\n`;
      component.labels.forEach((lbl) => {
        const cls = lbl.type === 'title' ? 'cad-label' : 'cad-sublabel';
        svg += `    <text x="${lbl.position.x}" y="${lbl.position.y}" class="${cls}">${lbl.text}</text>\n`;
      });
    }

    svg += `  </g>\n`;
  });

  svg += `</svg>`;
  return svg;
}
